import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import SmoothScrollProvider from "@/components/SmoothScrollProvider";
import Menu from "@/components/Menu/Menu";
import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Khaled A. Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[url("/slide/bg16.avif")] bg-contain bg-center`}
      >
        {/* <SmoothScrollProvider> */}
        <Menu />
        {children}
        <Footer />
        {/* </SmoothScrollProvider> */}
      </body>
    </html>
  );
}
